[tool.poetry]
name = "wavetopbox"
version = "0.1.0"
description = "WaveTop Box"
authors = ["Alex <temper8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
